/**
 * Shared Gemini helpers for the Supabase Edge Functions.
 *
 * Embeddings are generated by calling the Gemini v1beta REST endpoint
 * directly rather than through `@google/generative-ai`. The SDK's
 * `embedContent` typings do not expose `outputDimensionality`, so passing it
 * only works by accident (the object is forwarded verbatim as the request
 * body) and fails `deno check`. Because `grant_chunks.embedding` is declared
 * `vector(768)`, an embedding of any other arity makes Postgres reject the
 * insert, so the dimensionality must be explicit and verified.
 */

export const EMBEDDING_MODEL = 'gemini-embedding-001';
export const EMBEDDING_DIMENSIONS = 768;
export const CHAT_MODEL = 'gemini-2.5-flash';

const GEMINI_BASE = 'https://generativelanguage.googleapis.com/v1beta';

export class EmbeddingError extends Error {}

// 429 (daily free-tier quota, 20 requests/day/model) and 503 ("high demand") are the two Gemini
// answers a user meets in practice (measured 2026-09-25). They get ONE retry, then a typed error
// the edge functions turn into a Hungarian message; the raw Google text never reaches the client.
export type GeminiUnavailableCode = 'gemini_quota' | 'gemini_busy';

// A 200 answer can still be unusable: cut off at the token cap (finishReason MAX_TOKENS) or not
// valid JSON. Measured 2026-10-07: generate-document got a JSON cut off at character 124 and the
// bare JSON.parse threw a raw SyntaxError (card 6c7049fa #12).
export type GeminiOutputCode = 'gemini_truncated' | 'gemini_bad_output';

export const GEMINI_USER_MESSAGES: Record<GeminiUnavailableCode | GeminiOutputCode, string> = {
  gemini_quota: 'A napi AI-keret elfogyott, holnap 09:00 után próbáld újra.',
  gemini_busy: 'Az AI-szolgáltatás átmenetileg túlterhelt, próbáld újra egy perc múlva.',
  gemini_truncated: 'Az AI válasza félbeszakadt, ezért a dokumentum nem készült el. Próbáld újra.',
  gemini_bad_output: 'Az AI hibás formátumú választ adott, ezért a dokumentum nem készült el. Próbáld újra.',
};

export class GeminiUnavailableError extends Error {
  readonly code: GeminiUnavailableCode;
  readonly status: 429 | 503;
  constructor(status: 429 | 503) {
    const code: GeminiUnavailableCode = status === 429 ? 'gemini_quota' : 'gemini_busy';
    super(GEMINI_USER_MESSAGES[code]);
    this.code = code;
    this.status = status;
  }
}

export class GeminiOutputError extends Error {
  readonly code: GeminiOutputCode;
  readonly finishReason: string | null;
  constructor(code: GeminiOutputCode, finishReason: string | null) {
    super(GEMINI_USER_MESSAGES[code]);
    this.code = code;
    this.finishReason = finishReason;
  }
}

export interface GeminiDeps {
  fetch: typeof fetch;
  sleep: (ms: number) => Promise<void>;
}

const defaultDeps: GeminiDeps = {
  fetch: (...args) => fetch(...args),
  sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
};

/** The longest wait an edge function spends on the single retry. */
export const MAX_RETRY_WAIT_MS = 30_000;
const DEFAULT_RETRY_WAIT_MS = 2_000;

/**
 * How long to wait before the one retry, from Google's RetryInfo ("retryDelay": "12s") or the
 * Retry-After header; null when the wait would exceed MAX_RETRY_WAIT_MS (an exhausted daily
 * quota), because then a retry inside the request cannot succeed.
 */
export function retryWaitMs(res: Response, bodyText: string): number | null {
  let seconds: number | null = null;
  const m = bodyText.match(/"retryDelay"\s*:\s*"(\d+(?:\.\d+)?)s"/);
  if (m) seconds = Number(m[1]);
  else {
    const h = res.headers.get('retry-after');
    if (h && /^\d+(\.\d+)?$/.test(h.trim())) seconds = Number(h.trim());
  }
  const ms = seconds === null ? DEFAULT_RETRY_WAIT_MS : Math.ceil(seconds * 1000);
  return ms > MAX_RETRY_WAIT_MS ? null : ms;
}

/**
 * fetch with ONE retry on 429/503. Returns the response when it is ok or a different error; throws
 * GeminiUnavailableError when 429/503 persists (or the retry wait would be too long).
 */
async function fetchWithGeminiRetry(url: string, init: RequestInit, deps: GeminiDeps, label: string): Promise<Response> {
  for (let attempt = 0; attempt < 2; attempt++) {
    const res = await deps.fetch(url, init);
    if (res.status !== 429 && res.status !== 503) return res;
    const detail = await res.text();
    console.error(`Gemini ${label} hiba (${res.status}, próbálkozás ${attempt + 1}/2):`, detail);
    const wait = retryWaitMs(res, detail);
    if (attempt === 1 || wait === null) throw new GeminiUnavailableError(res.status as 429 | 503);
    await deps.sleep(wait);
  }
  throw new Error('unreachable');
}

/** JSON response for a GeminiUnavailableError: {code, error} with the 429/503 status. */
export function geminiUnavailableResponse(err: GeminiUnavailableError, headers: Record<string, string>, extra: Record<string, unknown> = {}): Response {
  return new Response(JSON.stringify({ code: err.code, error: err.message, ...extra }), {
    status: err.status,
    headers: { ...headers, 'Content-Type': 'application/json' },
  });
}

/**
 * Generates a 768-dimensional embedding for `text`.
 *
 * @throws {EmbeddingError} if the API call fails or returns a vector whose
 * arity does not match the `vector(768)` column, which would otherwise
 * surface much later as an opaque Postgres insert failure.
 */
export async function generateEmbedding(text: string, apiKey: string, deps: GeminiDeps = defaultDeps): Promise<number[]> {
  const res = await fetchWithGeminiRetry(
    `${GEMINI_BASE}/models/${EMBEDDING_MODEL}:embedContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: `models/${EMBEDDING_MODEL}`,
        content: { parts: [{ text }] },
        outputDimensionality: EMBEDDING_DIMENSIONS,
      }),
    },
    deps,
    'embedding',
  );

  if (!res.ok) {
    // Body is read for the server log only; callers must not forward it to
    // end users because it can echo request metadata.
    const detail = await res.text();
    console.error(`Gemini embedding hiba (${res.status}):`, detail);
    throw new EmbeddingError(`Embedding generálás sikertelen (${res.status})`);
  }

  const json = await res.json();
  const values = json?.embedding?.values;

  if (!Array.isArray(values)) {
    throw new EmbeddingError('A Gemini embedding válasz nem tartalmazott vektort.');
  }
  if (values.length !== EMBEDDING_DIMENSIONS) {
    throw new EmbeddingError(
      `Váratlan embedding dimenzió: ${values.length} (elvárt: ${EMBEDDING_DIMENSIONS})`,
    );
  }

  return values;
}

export interface GenerateOptions {
  model?: string;
  temperature?: number;
  responseMimeType?: string;
  /** Cap on the answer; on gemini-2.5-flash the thinking tokens count against it too. */
  maxOutputTokens?: number;
  /** 0 turns thinking off, so the whole cap goes to the answer. */
  thinkingBudget?: number;
  systemInstruction?: string;
}

/**
 * Calls a Gemini text model and returns the raw text of the first candidate.
 *
 * @throws {GeminiUnavailableError} on 429/503 after the one retry.
 */
export async function generateText(
  prompt: string,
  apiKey: string,
  options: GenerateOptions = {},
  deps: GeminiDeps = defaultDeps,
): Promise<string> {
  return (await generateCandidate(prompt, apiKey, options, deps)).text;
}

/** The first candidate's text and why it ended (STOP, MAX_TOKENS, SAFETY...). */
async function generateCandidate(
  prompt: string,
  apiKey: string,
  options: GenerateOptions,
  deps: GeminiDeps,
): Promise<{ text: string; finishReason: string | null }> {
  const model = options.model ?? CHAT_MODEL;
  const res = await fetchWithGeminiRetry(`${GEMINI_BASE}/models/${model}:generateContent?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      ...(options.systemInstruction ? { systemInstruction: { parts: [{ text: options.systemInstruction }] } } : {}),
      generationConfig: {
        temperature: options.temperature ?? 0.2,
        ...(options.responseMimeType ? { responseMimeType: options.responseMimeType } : {}),
        ...(options.maxOutputTokens ? { maxOutputTokens: options.maxOutputTokens } : {}),
        ...(options.thinkingBudget !== undefined ? { thinkingConfig: { thinkingBudget: options.thinkingBudget } } : {}),
      },
    }),
  }, deps, 'generateContent');

  if (!res.ok) {
    const detail = await res.text();
    console.error(`Gemini generateContent hiba (${res.status}):`, detail);
    throw new Error(`Gemini hívás sikertelen (${res.status})`);
  }

  const json = await res.json();
  const candidate = json?.candidates?.[0];
  const text = candidate?.content?.parts?.[0]?.text;
  const finishReason: string | null = candidate?.finishReason ?? null;
  if (typeof text !== 'string') {
    console.error(`Gemini válasz szöveg nélkül (finishReason: ${finishReason}).`);
    throw new Error('A Gemini válasz nem tartalmazott szöveget.');
  }
  return { text, finishReason };
}

/**
 * Calls Gemini for a JSON answer and parses it. An answer cut off at the token cap (MAX_TOKENS) or
 * not parseable gets ONE more attempt, then a typed GeminiOutputError with a Hungarian message;
 * the finishReason is logged on every failed attempt so the server log says why.
 *
 * @throws {GeminiUnavailableError} on 429/503 after the one retry.
 * @throws {GeminiOutputError} when both attempts give a cut-off or broken answer.
 */
export async function generateJson<T>(
  prompt: string,
  apiKey: string,
  options: GenerateOptions = {},
  deps: GeminiDeps = defaultDeps,
): Promise<T> {
  let last: GeminiOutputError | null = null;
  for (let attempt = 1; attempt <= 2; attempt++) {
    const { text, finishReason } = await generateCandidate(prompt, apiKey, { responseMimeType: 'application/json', ...options }, deps);
    if (finishReason === 'MAX_TOKENS') {
      last = new GeminiOutputError('gemini_truncated', finishReason);
    } else {
      try {
        return parseJsonFromModel<T>(text);
      } catch {
        last = new GeminiOutputError('gemini_bad_output', finishReason);
      }
    }
    console.error(`Gemini JSON-válasz használhatatlan (${last.code}, finishReason: ${finishReason}, ${text.length} karakter, próbálkozás ${attempt}/2).`);
  }
  throw last!;
}

/**
 * Extracts a JSON value from a model response, tolerating the fenced code
 * blocks that Gemini frequently emits even when JSON output is requested.
 */
export function parseJsonFromModel<T>(raw: string): T {
  const cleaned = raw
    .trim()
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/, '');

  try {
    return JSON.parse(cleaned) as T;
  } catch {
    // Fall back to the outermost JSON object/array in the response.
    const match = cleaned.match(/[[{][\s\S]*[\]}]/);
    if (!match) {
      throw new Error('A modell válaszából nem sikerült JSON-t kinyerni.');
    }
    return JSON.parse(match[0]) as T;
  }
}
