/**
 * Shared Gemini helpers for the Supabase Edge Functions.
 *
 * Embeddings are generated by calling the Gemini v1beta REST endpoint
 * directly rather than through `@google/generative-ai`. The SDK's
 * `embedContent` typings do not expose `outputDimensionality`, so passing it
 * only works by accident (the object is forwarded verbatim as the request
 * body) and fails `deno check`. Because `grant_chunks.embedding` is declared
 * `vector(768)`, an embedding of any other arity makes Postgres reject the
 * insert, so the dimensionality must be explicit and verified.
 */

export const EMBEDDING_MODEL = 'gemini-embedding-001';
export const EMBEDDING_DIMENSIONS = 768;
export const CHAT_MODEL = 'gemini-2.5-flash';

const GEMINI_BASE = 'https://generativelanguage.googleapis.com/v1beta';

export class EmbeddingError extends Error {}

/**
 * Generates a 768-dimensional embedding for `text`.
 *
 * @throws {EmbeddingError} if the API call fails or returns a vector whose
 * arity does not match the `vector(768)` column, which would otherwise
 * surface much later as an opaque Postgres insert failure.
 */
export async function generateEmbedding(text: string, apiKey: string): Promise<number[]> {
  const res = await fetch(
    `${GEMINI_BASE}/models/${EMBEDDING_MODEL}:embedContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: `models/${EMBEDDING_MODEL}`,
        content: { parts: [{ text }] },
        outputDimensionality: EMBEDDING_DIMENSIONS,
      }),
    },
  );

  if (!res.ok) {
    // Body is read for the server log only; callers must not forward it to
    // end users because it can echo request metadata.
    const detail = await res.text();
    console.error(`Gemini embedding hiba (${res.status}):`, detail);
    throw new EmbeddingError(`Embedding generálás sikertelen (${res.status})`);
  }

  const json = await res.json();
  const values = json?.embedding?.values;

  if (!Array.isArray(values)) {
    throw new EmbeddingError('A Gemini embedding válasz nem tartalmazott vektort.');
  }
  if (values.length !== EMBEDDING_DIMENSIONS) {
    throw new EmbeddingError(
      `Váratlan embedding dimenzió: ${values.length} (elvárt: ${EMBEDDING_DIMENSIONS})`,
    );
  }

  return values;
}

/**
 * Calls a Gemini text model and returns the raw text of the first candidate.
 */
export async function generateText(
  prompt: string,
  apiKey: string,
  options: { model?: string; temperature?: number; responseMimeType?: string } = {},
): Promise<string> {
  const model = options.model ?? CHAT_MODEL;
  const res = await fetch(`${GEMINI_BASE}/models/${model}:generateContent?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: options.temperature ?? 0.2,
        ...(options.responseMimeType ? { responseMimeType: options.responseMimeType } : {}),
      },
    }),
  });

  if (!res.ok) {
    const detail = await res.text();
    console.error(`Gemini generateContent hiba (${res.status}):`, detail);
    throw new Error(`Gemini hívás sikertelen (${res.status})`);
  }

  const json = await res.json();
  const text = json?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (typeof text !== 'string') {
    throw new Error('A Gemini válasz nem tartalmazott szöveget.');
  }
  return text;
}

/**
 * Extracts a JSON value from a model response, tolerating the fenced code
 * blocks that Gemini frequently emits even when JSON output is requested.
 */
export function parseJsonFromModel<T>(raw: string): T {
  const cleaned = raw
    .trim()
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/, '');

  try {
    return JSON.parse(cleaned) as T;
  } catch {
    // Fall back to the outermost JSON object/array in the response.
    const match = cleaned.match(/[[{][\s\S]*[\]}]/);
    if (!match) {
      throw new Error('A modell válaszából nem sikerült JSON-t kinyerni.');
    }
    return JSON.parse(match[0]) as T;
  }
}
